apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monorepo-application-set
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/SamTheisens/mpyl-gha-example.git
        revision: HEAD
        directories:
          - path: argocd/manifests/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/SamTheisens/mpyl-gha-example.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true