kind: Simple
apiVersion: k3d.io/v1alpha3
name: mpyl-argocd
servers: 1
agents: 0
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
ports:
  - port: 9080:80
    nodeFilters:
      - loadbalancer
  - port: 0.0.0.0:9443:443
    nodeFilters:
      - loadbalancer
