apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mpyl-example-argocd
spec:
  generators:
    - matrix:
        generators:
          - pullRequest:
              github:
                owner: SamTheisens
                repo: mpyl-example-argocd
              requeueAfterSeconds: 60
          - git:
              repoURL: https://github.com/SamTheisens/mpyl-example-argocd.git
              revision: '{{head_sha}}'
              directories:
                - path: manifests/projects/*
  template:
    metadata:
      name: 'pr-{{number}}-{{path.basename}}'
      labels:
        pull-request: '{{number}}'
    spec:
      destination:
        namespace: 'pr-{{number}}'
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: '{{path}}'
        repoURL: https://github.com/SamTheisens/mpyl-example-argocd.git
        targetRevision: '{{head_sha}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true